routes:
  admin/reports/documentation/at_base:
    title: AT Base
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Reports\Routes', 'render']
    type: constant('MENU_LOCAL_TASK')
    weight: -200

  admin/reports/documentation/at_base/routes:
    title: Routes
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Reports\Routes', 'render']
    type: constant('MENU_DEFAULT_LOCAL_TASK')

  admin/reports/documentation/at_base/source:
    title: Modules List
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Reports\SourceCode\ModuleIndex', 'render']
    type: constant('MENU_LOCAL_TASK')
    weight: 100

  'admin/reports/documentation/at_base/source/%':
    title: Source
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Reports\SourceCode', 'render', [5]]
    weight: 100

  admin/reports/documentation/at_base/entity-templates:
    title: Entity templates
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Reports\Entity_Templates', 'render']
    type: constant('MENU_LOCAL_TASK')

  'at/icon':
    title: Icons
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Icons', 'renderServices']

  'at/icon/%':
    title: Icons
    access arguments: ['at-doc access']
    controller: ['Drupal\at_ui\Controller\Icons', 'renderServiceSets']
    breadcrumbs:
      - ['Home', '<front>']
      - ['Icons', 'at/icon']

  'at/icon/%/%':
    title: Icons
    access arguments: ['at-doc access']
    controller:
      - 'Drupal\at_ui\Controller\Icons'
      - 'renderServiceSet'
      - { service_name: 2, set_name: 3 }
    before:
      - ['drupal_add_library', ['system', 'ui.dialog']]
    attached:
      css:
        - '%datatables/media/css/jquery.dataTables.css'
        - '@at_ui/misc/css/at.icon.css'
      js:
        - '%datatables/media/js/jquery.dataTables.min.js'
        - '@at_ui/misc/js/at.icon.js'
    breadcrumbs:
      - ['Home', '<front>']
      - ['Icons', 'at/icon']

  at/sql:
    title: Execute SQL Query
    # Permisison defined by devel.module
    access arguments: ['execute php code']
    file: at_ui.atsql.inc
    page callback: drupal_get_form
    page arguments: ['at_ui_sql_form']
    before:
      - [at_ui_include_codemirror, [['mode/sql/sql.js']]]
      - [drupal_add_js,  ['@at_ui/misc/js/at.sql.js']]
      - [drupal_add_css, ['@at_ui/misc/css/cm.css']]

  at/twig:
    title: Twig Form
    access arguments: ['execute php code']
    file: at_ui.codemirror.attwig.inc
    page callback: drupal_get_form
    page arguments: ['at_ui_twig_form']
    form: 'Drupal\at_ui\Controller\TwigFormController'
    form arguments: []
    before:
      - [at_ui_include_codemirror, [['mode/htmlmixed/htmlmixed.js', 'mode/xml/xml.js', 'addon/mode/overlay.js']]]
      - [drupal_add_js, ['@at_ui/misc/js/at.twig.js']]
      - [drupal_add_css, ['@at_ui/misc/css/cm.css']]

  'at/twig/views':
    title: drupalView
    access arguments: ['execute php code']
    file: at_ui.codemirror.attwig.inc
    page callback: drupal_get_form
    page arguments: ['at_ui_twig_views_form']
